import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/events">Events</Link>
            </li>
            <li>
              <Link href="/about-us">About-us</Link>
            </li>
            <li>
              <Link href="/comments">Comments</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="home-container">
        {data.map((event) => (
          <div key={event.id}>
            <Link href={`/events/${event.id}`}>
              <img src={event.image} alt={event.title} />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </Link>
          </div>
        ))}
      </main>
      <footer>
        <hr />
        <p> &copy; 2022 time to Party</p>
      </footer>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  return {
    props: {
      data: events_categories,
    },
  };
}
